### ISSUE TITLE
DirectX Raytracing - Sample pack 

### ISSUE THREAD

**Issue by johannesugb** [NVIDIAGameWorks/DxrTutorials#10]
I am not sure what's the best way to contact Nvidia/Nir Benty about this, so I'll try just here:

At the end of Nir Benty's talk about Falcor during the GDC session "The Ray + Raster Era Begins: An R&D roadmap for the game industry",  a sample pack has been promised (see [1] at 53:34). I wanted to ask if that samples pack is already available somewhere or when it will be released.

I am especially interested in denoiser examples, because I haven't been able to find any of these yet. There is a lot being talked about denoisers in the GDC talk "Ray Tracing in Games with NVIDIA RTX" [2], like that different denoisers have to be applied depending on the kind of data. I am wondering if these are stock denoisers (as they appear to be included with OptiX) and if so, how they can be used. 

Thanks!

[1] https://youtu.be/Q8e3rFkLZUg?t=3274
[2] https://youtu.be/EFLimT4ik_8

**Comment by nbentyNV** [comment]
We're working on it, should have SVGF sample soon.
It will be released as a Falcor sample - https://github.com/NVIDIAGameWorks/Falcor
