### ISSUE TITLE
Error Running

### ISSUE THREAD

**Issue by OptimisticMonkey** [NVIDIAGameWorks/DxrTutorials#13]
Seems to build ok... but running 01-CreateWindow causes:

"The application was unable to start correctly(0xc0000007b)"

Have latest Windows build 1809 and SDK, GTX 2080 Ti, latest drivers....

**Comment by nbentyNV** [comment]
@OptimisticMonkey Please make sure you are building the x64 configuration.

@kyaoNV Please delete the x86 config from the solution

**Comment by gamerx1221** [comment]
Hi same issue, please advise.  tried release mode, same problem.

**Comment by nbentyNV** [comment]
Are you building x86 or x64?

**Comment by gamerx1221** [comment]
x64; found out problem, had to copy python.dll from dxrTutorials folder, not using python install from windows. version mismatch!! now different error when running tutorials.   

Sample::run(config, pSample); throws error, pSample is fine going in, at time of error is empty
this happens in winmain function.

Unhandled exception at 0x00007FFAFDA4E57E (ucrtbase.dll) in 02-InitDXR.exe: Fatal program exit requested.

any help is appreciated!

**Comment by nbentyNV** [comment]
I'll take a look

**Comment by nbentyNV** [comment]
Sorry for that, the latest version of Falcor introduced a dependency on python.
I removed the dependency and implemented a new `Framework` class which abstracts the windowing.
There are no external dependencies, the repo is completely self-contained.

**Comment by OptimisticMonkey** [comment]
Worked :-)

**Comment by gamerx1221** [comment]
that's great.  still having an issue upgrading to 1809 here, will have to wait until they automatically do the update using windows update.  manually updating doesn't work from 1803.
