### ISSUE TITLE
Have you removed the Falcor framework?

### ISSUE THREAD

**Issue by bipul-mohanto** [NVIDIAGameWorks/DxrTutorials#17]
Hi,

Sorry to ask naive question, but this repository seems like simple implementation without Falcor framework, am I right?

**Comment by kyaoNV** [comment]
Yes it was removed in https://github.com/NVIDIAGameWorks/DxrTutorials/commit/e697789fe4652909d279203e6ebd7d808bd74535

**Comment by bipul-mohanto** [comment]
Isn't Falcor a good choice for DX12?
