### ISSUE TITLE
D3D12EnableExperimentalFeatures causes failure to create device

### ISSUE THREAD

**Issue by emanuelshalev** [NVIDIAGameWorks/DxrTutorials#2]
trying to run the tutorials.
My adapter supports D3D_FEATURE_LEVEL_12_0 but the D3D12EnableExperimentalFeatures is causing the create device call to fail.
If I remove the D3D12EnableExperimentalFeatures the D3D12CreateDevice works fine, but then other crashes occur.

I am using a GTX 1050 TI with the latest nvidia driver and the lates windows insider update.
the recently released DXRSDK_v0.09.01 compiles and run fine for me.

Is there any special hardware requirement related to the EnableExperimentalFeatures call?

thanks,
Emanuel

**Comment by nbentyNV** [comment]
I'll need to add support for the fallback layer, it might take some time.

**Comment by oscarbg** [comment]
Just a question: nvidia driver 396.xx supporting RTX and DXR will avoid need for fallback layer in pre Volta cards like Pascal and Maxwell?

**Comment by nbentyNV** [comment]
No. RTX requires Volta.

**Comment by sayan1an** [comment]
@nbenty Do you have a roadmap for supporting the fallback layer? I'm also running 1050 and would love to prototype on my laptop.

**Comment by nbentyNV** [comment]
The tutorials will not support the fallback layer. There are intended to show how to use the official API, and the fallback layer's API is different in many places

**Comment by aligili** [comment]
Emanuel,
I am having same issue with a call to D3D12EnableExperimentalFeatures. It returns true but it causes later CreateDevice to fail. Have you managed to fix it? 

I use Nvidia Geforce GTX 1050

**Comment by nbentyNV** [comment]
GTX 1050 doesn't support DXR
