### ISSUE TITLE
entry point not found

### ISSUE THREAD

**Issue by Sumenia** [NVIDIAGameWorks/DxrTutorials#3]
Hi,

I wanted to try this out on my AMD Vega 56 but i fail to run any sample. Is this Nvidia only ?

```
The procedure entry point D3DKMTOpenBundleObjectNtHandleFromName could not be located in the dynamic link library d3d12.dll
```

**Comment by nbentyNV** [comment]
It's not NVIDIA only.
You'll need a driver/HW that supports DirectX Raytracing. I don't know which AMD HW supports that.
