### ISSUE TITLE
Project Can t Run: Can not locate the program entry 

### ISSUE THREAD

**Issue by ArionTT** [NVIDIAGameWorks/DxrTutorials#4]
I have download the project and open it with VS2015 community. The other assets (i.e. freeimg dear_imgui etc.) have been downloaded.

At first ,I build it and run. VS tell me I lose some dll. I copy the assets dll to the path: DxrTutorials/Bin/x64/Debug.

Then it tell me, that:

 **"Can not locacte program entry point D3DKMTOpenBundleObjectNtHandleFromName in dynamic library F:\Project\DirectX12\DxrTutorials\Bin\x64\Debug\d3d12.dll"**

Did i lose some files or make some mistakes?

screenshot:
MyDebugPath
![20180424164326](https://user-images.githubusercontent.com/21036443/39176195-d173bfcc-47de-11e8-935e-fb08ee69794b.png)

**Comment by nbentyNV** [comment]
You need a GPU and a driver which supports DXR.

**Comment by ArionTT** [comment]
Can this sample run on DirectX12 Fallback Layer？

My graphic card is NVIDIA GeForce GTX 1050Ti.

**Comment by nbentyNV** [comment]
No. The tutorials were designed to run with the official API.
Unfortunately, the fallback layer requires significant code changes. For the purpose of clarity, we chose to focus on the official API only.
