### ISSUE TITLE
It doesn't compile #2

### ISSUE THREAD

**Issue by andreluizgit** [NVIDIAGameWorks/DxrTutorials#6]
1>------ Compilação iniciada: Projeto: 01-CreateWindow, Configuração: Debug x64 ------
1>Fetching packman-common@5.3.1.zip from S3 ...
1>Connecting to S3 ...
1>Downloading ...
1>Unpacking ...
1>  File "C:\IntelPython3\Lib\site.py", line 177
1>    file=sys.stderr)
1>        ^
1>SyntaxError: invalid syntax
1>!!! Failure while configuring local machine :( !!!
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: O comando "call C:\Users\andre\Source\Repos\DxrTutorials\\Framework\BuildScripts\prebuild.bat C:\Users\andre\Source\Repos\DxrTutorials\\.\.\.\.\.\.\.\.\.\.\.\.\.\Framework\ C:\Users\andre\Source\Repos\DxrTutorials\ C:\Users\andre\Source\repos\DxrTutorials\Tutorials\01-CreateWindow\ x64 x64 Debug C:\Users\andre\Source\Repos\DxrTutorials\Bin\x64\Debug\
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd" foi encerrado com o código 1.
1>Projeto de compilação pronto "01-CreateWindow.vcxproj" -- FALHA.
2>------ Compilação iniciada: Projeto: 03-AccelerationStructure, Configuração: Debug x64 ------
3>------ Compilação iniciada: Projeto: 04-RtPipelineState, Configuração: Debug x64 ------
4>------ Compilação iniciada: Projeto: 06-Raytrace, Configuração: Debug x64 ------
5>------ Compilação iniciada: Projeto: 07-BasicShaders, Configuração: Debug x64 ------
6>------ Compilação iniciada: Projeto: 08-Instancing, Configuração: Debug x64 ------
7>------ Compilação iniciada: Projeto: 09-ConstantBuffer, Configuração: Debug x64 ------
8>------ Compilação iniciada: Projeto: 10-PerInstanceConstantBuffer, Configuração: Debug x64 ------
9>------ Compilação iniciada: Projeto: 11-SecondGeometry, Configuração: Debug x64 ------
2>03-AccelerationStructure.cpp
3>04-RtPipelineState.cpp
4>06-Raytrace.cpp
5>07-BasicShaders.cpp
9>11-SecondGeometry.cpp
6>08-Instancing.cpp
7>09-ConstantBuffer.cpp
8>10-PerInstanceConstantBuffer.cpp
4>c:\users\andre\source\repos\dxrtutorials\tutorials\06-raytrace\06-raytrace.h(35): fatal error C1083: Não é possível abrir arquivo incluir: 'Falcor.h': No such file or directory
2>c:\users\andre\source\repos\dxrtutorials\tutorials\03-accelerationstructure\03-accelerationstructure.h(35): fatal error C1083: Não é possível abrir arquivo incluir: 'Falcor.h': No such file or directory
3>c:\users\andre\source\repos\dxrtutorials\tutorials\04-rtpipelinestate\04-rtpipelinestate.h(35): fatal error C1083: Não é possível abrir arquivo incluir: 'Falcor.h': No such file or directory
5>c:\users\andre\source\repos\dxrtutorials\tutorials\07-basicshaders\07-basicshaders.h(35): fatal error C1083: Não é possível abrir arquivo incluir: 'Falcor.h': No such file or directory
9>c:\users\andre\source\repos\dxrtutorials\tutorials\11-secondgeometry\11-secondgeometry.h(35): fatal error C1083: Não é possível abrir arquivo incluir: 'Falcor.h': No such file or directory
7>c:\users\andre\source\repos\dxrtutorials\tutorials\09-constantbuffer\09-constantbuffer.h(35): fatal error C1083: Não é possível abrir arquivo incluir: 'Falcor.h': No such file or directory
8>c:\users\andre\source\repos\dxrtutorials\tutorials\10-perinstanceconstantbuffer\10-perinstanceconstantbuffer.h(35): fatal error C1083: Não é possível abrir arquivo incluir: 'Falcor.h': No such file or directory
6>c:\users\andre\source\repos\dxrtutorials\tutorials\08-instancing\08-instancing.h(35): fatal error C1083: Não é possível abrir arquivo incluir: 'Falcor.h': No such file or directory
9>Projeto de compilação pronto "11-SecondGeometry.vcxproj" -- FALHA.
3>Projeto de compilação pronto "04-RtPipelineState.vcxproj" -- FALHA.
2>Projeto de compilação pronto "03-AccelerationStructure.vcxproj" -- FALHA.
5>Projeto de compilação pronto "07-BasicShaders.vcxproj" -- FALHA.
10>------ Compilação iniciada: Projeto: 12-PerGeometryHitShader, Configuração: Debug x64 ------
7>Projeto de compilação pronto "09-ConstantBuffer.vcxproj" -- FALHA.
4>Projeto de compilação pronto "06-Raytrace.vcxproj" -- FALHA.
6>Projeto de compilação pronto "08-Instancing.vcxproj" -- FALHA.
8>Projeto de compilação pronto "10-PerInstanceConstantBuffer.vcxproj" -- FALHA.
11>------ Compilação iniciada: Projeto: 13-SecondRayType, Configuração: Debug x64 ------
12>------ Compilação iniciada: Projeto: 14-Refit, Configuração: Debug x64 ------
13>------ Compilação iniciada: Projeto: 02-InitDXR, Configuração: Debug x64 ------
14>------ Compilação iniciada: Projeto: 05-ShaderTable, Configuração: Debug x64 ------
10>12-PerGeometryHitShader.cpp
11>13-SecondRayType.cpp
12>14-Refit.cpp
13>02-InitDXR.cpp
14>05-ShaderTable.cpp
10>c:\users\andre\source\repos\dxrtutorials\tutorials\12-pergeometryhitshader\12-pergeometryhitshader.h(36): fatal error C1083: Não é possível abrir arquivo incluir: 'Falcor.h': No such file or directory
11>c:\users\andre\source\repos\dxrtutorials\tutorials\13-secondraytype\13-secondraytype.h(35): fatal error C1083: Não é possível abrir arquivo incluir: 'Falcor.h': No such file or directory
12>c:\users\andre\source\repos\dxrtutorials\tutorials\14-refit\14-refit.h(35): fatal error C1083: Não é possível abrir arquivo incluir: 'Falcor.h': No such file or directory
13>c:\users\andre\source\repos\dxrtutorials\tutorials\02-initdxr\02-initdxr.h(35): fatal error C1083: Não é possível abrir arquivo incluir: 'Falcor.h': No such file or directory
14>c:\users\andre\source\repos\dxrtutorials\tutorials\05-shadertable\05-shadertable.h(35): fatal error C1083: Não é possível abrir arquivo incluir: 'Falcor.h': No such file or directory
10>Projeto de compilação pronto "12-PerGeometryHitShader.vcxproj" -- FALHA.
12>Projeto de compilação pronto "14-Refit.vcxproj" -- FALHA.
11>Projeto de compilação pronto "13-SecondRayType.vcxproj" -- FALHA.
13>Projeto de compilação pronto "02-InitDXR.vcxproj" -- FALHA.
14>Projeto de compilação pronto "05-ShaderTable.vcxproj" -- FALHA.
========== Compilar: 0 com êxito, 14 com falha, 0 atualizados, 0 ignorados ==========

**Comment by nbentyNV** [comment]
@halldorfannar It works on my machine. Any clue as to why packman fails? Could it be a localization issue?

**Comment by halldorfannar** [comment]
This is baffling, to say the least.  The log implies that there is an existing Python3 installation on that machine that is somehow interfering with packman.  I need to research how that can happen.

In the meantime, @andreluizgit can you please delete your `%PM_PACKAGES_ROOT%` directory and try building again?  Please post the log here. The log above doesn't show packman fetching the Python interpreter and I want to make sure this is happening when you have an non-existent packman cache.

**Comment by halldorfannar** [comment]
OK, I have a theory. Please modify this line:

https://github.com/NVIDIAGameWorks/DxrTutorials/blob/fae62d5d5a1fae35c8db777a56acf745b3a7959d/Framework/Source/packman/win-bootstrap/configure.bat#L105 

To read:
```
@"%PM_PYTHON%" -s "%~dp0\install_package.py" "%TARGET%" "%PM_MODULE_DIR%"
```
That is, we add the `-s` option to disable the site.py importing mechanism in Python which may be causing the problem.  My theory is that this will get you past the step of setting up packman-common but you will still experience a failure on the next invocation of Python in that script.  Once we have confirmed that this solves the issue we can add `-s` to all places in the script where `%PM_PYTHON%` is called.

**Comment by nbentyNV** [comment]
Is this still an issue?

**Comment by andreluizgit** [comment]
I will try again... sorry for delay...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by johannesugb** [comment]
The solution for me was to uninstall Python. ¯\\_(ツ)_/¯
Don't forget to remove the PYTHON_HOME environment variable!

**Comment by halldorfannar** [comment]
In the newer versions of packman these issues have been guarded against.  We should upgrade the repo to latest version of packman.

**Comment by nbentyNV** [comment]
@kyaoNV Please upgrade Packman (on Falcor as well) as part of the RS5 work
