### ISSUE TITLE
The specified device interface or feature level is not supported on this system.

### ISSUE THREAD

**Issue by krupitskas** [NVIDIAGameWorks/DxrTutorials#7]
I can't run second tutorial with that problem. 
[DxDiag.txt](https://github.com/NVIDIAGameWorks/DxrTutorials/files/2248808/DxDiag.txt)

**Comment by nbentyNV** [comment]
Your GPU doesn't support DXR. You can only use the fallback layer which these tutorials do not support

**Comment by krupitskas** [comment]
Ah okay, sry. 
Can you add this point to requirements in README.md?
Thanks :)

**Comment by Mayhem50** [comment]
I have a GV100 and the same message. Should I get specific driver version ? I'm currently running 391.89.

**Comment by nbentyNV** [comment]
@Mayhem50 391.89 doesn't support DXR. Please get the latest driver (I'm using 398.82)

**Comment by izikhuang** [comment]
i got the same error and my gpu is 1080 with driver 411.63

[DxDiag.txt](https://github.com/NVIDIAGameWorks/DxrTutorials/files/2422233/DxDiag.txt)

**Comment by nbentyNV** [comment]
1080 doesn't support DXR
