### ISSUE TITLE
Fallback Layer

### ISSUE THREAD

**Issue by johannesugb** [NVIDIAGameWorks/DxrTutorials#8]
These samples do not include the fallback layer, do they?
Is support for the fallback layer planned anytime soon? 
If not, does it make any sense if I try to integrate it or will I likely have a bad time?

**Comment by nbentyNV** [comment]
You can try, I don't know how long it takes.
The fallback layer has a 3 page readme which describes the differences between the actual API and the fallback API, so it will take some time.

In any case, these tutorials are here to show how to use the actual API, so we will not add support for the fallback layer.
